### ISSUE TITLE
バックエンド側のproduction環境を用意する

### ISSUE THREAD

**Issue by kantaroso** [kantaroso/game-information#13]

**Comment by kantaroso** [comment]
以下の理由から ibmクラウド でやってみる

* 無料
* クレカ登録なしでできる

**Comment by kantaroso** [comment]
データベース：Db2

https://qiita.com/Asuka_Saito/items/c40a17f02a588953f576

アプリケーション：cf

https://qiita.com/n0bisuke/items/4c29aad3696edcc627f2

**Comment by kantaroso** [comment]
cf にお試しで下記をdeploy

```shell
$ curl http://gameinfomation.us-south.cf.appdomain.cloud/
Hello, World
```

<details>
<summary>内容メモ</summary>

* 一覧
```shell
$ tree
.
├── go.mod
├── go.sum
├── main
├── main.go
└── manifest.yml
```

* `main.go`
```go
package main

import (
	"os"

	"github.com/gin-gonic/gin"
)

func main() {
	r := gin.Default()
	r.GET("/", func(c *gin.Context) {
		c.String(200, "Hello, World")
	})
	r.GET("/health", func(c *gin.Context) {
		c.String(200, "OK")
	})
	port := os.Getenv("PORT")
	if port == "" {
		port = "8080" //Local
	}
	r.Run(":" + port)
}
```

* `manifest.yml`
```yml
 applications:
 - name: gameinfomation
   random-route: true
   memory: 64M
   env:
      GOVERSION: go1.14
```
</details>
