### ISSUE TITLE
ciで本番リリースする

### ISSUE THREAD

**Issue by kantaroso** [kantaroso/game-information#44]
## 概要

表題の通り

## 詳細

github Actions で 手動の workflow の実装してみたい

https://docs.github.com/ja/actions/using-workflows/events-that-trigger-workflows#workflow_dispatch

**Comment by kantaroso** [comment]
デフォルトブランチでしか動かないらしい

https://dev.classmethod.jp/articles/github-actions-workflow-dispatch-default-branch/


![スクリーンショット 2022-12-18 18 26 31](https://user-images.githubusercontent.com/51830444/208290851-178ad5c2-35fc-404d-b62f-4c948af034d4.png)

**Comment by kantaroso** [comment]
実行の方法


![スクリーンショット 2022-12-18 18 07 26](https://user-images.githubusercontent.com/51830444/208290881-11914fa4-635d-4af2-a4cf-ff8c1a6d7eea.png)

**Comment by kantaroso** [comment]
これでバックエンド -> フロントの順番でリリース出来る

```yml
name: deploy
on:
  workflow_dispatch:
    inputs:
      backend:
        description: 'backend release'
        default: false
        type: boolean
      frontend:
        description: 'frontend release'
        required: false
        type: boolean
jobs:
  deploy-backend:
    if: ${{ inputs.backend }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "deploy-backend"
  deploy-frontend:
    if: ${{ !failure() && inputs.frontend }}
    needs: deploy-backend
    runs-on: ubuntu-latest
    steps:
      - run: echo "deploy-frontend"

```

こうするとちゃんと後ろの実行とまる

```diff
     if: ${{ inputs.backend }}
     runs-on: ubuntu-latest
     steps:
-      - run: echo "deploy-backend"
+      - run: echoo "deploy-backend"
   deploy-frontend:
     if: ${{ !failure() && inputs.frontend }}
     needs: deploy-backend
```
![スクリーンショット 2022-12-18 18 32 32](https://user-images.githubusercontent.com/51830444/208291101-87d30580-415c-413a-9122-cdd11e5e14cd.png)
